name = "lppm-research-system"
compatibility_date = "2024-01-01"
pages_build_output_dir = "out"

[env.production.vars]
NEXT_PUBLIC_AUTH_WORKER_URL = "https://lppm-research-system.suhendararyadi.workers.dev"
NEXT_PUBLIC_RESEARCH_WORKER_URL = "https://lppm-research-system.suhendararyadi.workers.dev"
NEXT_PUBLIC_SERVICE_WORKER_URL = "https://lppm-research-system.suhendararyadi.workers.dev"
NEXT_PUBLIC_DOCUMENTS_WORKER_URL = "https://lppm-research-system.suhendararyadi.workers.dev"
NEXT_PUBLIC_NOTIFICATIONS_WORKER_URL = "https://lppm-research-system.suhendararyadi.workers.dev"
NEXT_PUBLIC_ENVIRONMENT = "production"
NEXT_PUBLIC_MOCK_DATA = "false"